# HOW TO RUN SYNERGY --------------------------------------------------
# synergy server should be run in the desktop pc using:
# synergys -n desktop
# then you should connect from the laptop using this command:
# synergyc -n laptop <ip_or_hostname_of_this_pc>
#
# NOTE: this config file is used by the synergy server (desktop) only
# ---------------------------------------------------------------------

section: screens
    laptop:
        # for the Command key to work on Mac
        alt = meta
        super = alt
    desktop:
end

section: links
    laptop:
        right = desktop
    desktop:
        left = laptop
end

section: options
    keystroke(control+Grave) = switchToScreen(laptop)
    keystroke(control+\) = switchToScreen(desktop)
end
