#!/bin/bash
# This hook is run after every virtualenv is activated.

_OLD_VIRTUAL_PS1="$PS1"
PS1="\[\033[01;33m\][`basename \"$VIRTUAL_ENV\"`] $PS1"

_OLD_VIRTUAL_PYTHONPATH="$PYTHONPATH"
export PYTHONPATH="$HOME/.virtualenv-libs:$PYTHONPATH"

_OLD_VIRTUAL_PATH="$PATH"
export PATH="~/src/scrapy/bin:$_OLD_VIRTUAL_PATH"
